// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jawquthfrpjmcdgmoaes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imphd3F1dGhmcnBqbWNkZ21vYWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Nzg4MTAsImV4cCI6MjA2MTA1NDgxMH0.TA66eHQ0CdTlP-LBuXgaxcxVd044R24OwkmChkncvbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);